/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import javax.swing.SwingUtilities;

/**
 *
 * @author YILBER
 */
public class vistalogin extends javax.swing.JFrame {

    /**
     * Creates new form vistalogin
     */
    public vistalogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSLabelImage11 = new rojerusan.RSLabelImage();
        rSLabelImage12 = new rojerusan.RSLabelImage();
        inputpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        inputusers = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        boton1 = new botones.boton();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelImage11.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelImage11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/COLCARMEN.png"))); // NOI18N
        jPanel1.add(rSLabelImage11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 100, 100));

        rSLabelImage12.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelImage12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/ideatech.png"))); // NOI18N
        jPanel1.add(rSLabelImage12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 220, 90));

        inputpassword.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        inputpassword.setForeground(new java.awt.Color(255, 102, 0));
        inputpassword.setSelectionColor(new java.awt.Color(255, 51, 0));
        jPanel1.add(inputpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 260, 252, 41));

        jLabel2.setFont(new java.awt.Font("Questions", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 215, -1, -1));

        inputusers.setFont(new java.awt.Font("Questions", 0, 24)); // NOI18N
        inputusers.setForeground(new java.awt.Color(255, 51, 0));
        inputusers.setCaretColor(new java.awt.Color(255, 51, 0));
        inputusers.setSelectionColor(new java.awt.Color(255, 51, 0));
        inputusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputusersActionPerformed(evt);
            }
        });
        jPanel1.add(inputusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 154, 252, 43));

        jLabel3.setFont(new java.awt.Font("Questions", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("USUARIO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 103, -1, -1));

        boton1.setBackground(new java.awt.Color(255, 102, 0));
        boton1.setForeground(new java.awt.Color(255, 255, 255));
        boton1.setText("ENTRAR :)");
        boton1.setFont(new java.awt.Font("Questions", 0, 36)); // NOI18N
        boton1.setRound(0);
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 313, -1, 49));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgLogin.png"))); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 426, 531));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        clases.validacionLogin objetoLogin = new clases.validacionLogin();
        objetoLogin.validaUsuario(inputusers, inputpassword, this);
    }//GEN-LAST:event_boton1ActionPerformed

    private void inputusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputusersActionPerformed

    }//GEN-LAST:event_inputusersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // Usar SwingUtilities para asegurar que el GUI se inicializa en el hilo de eventos de Swing
        SwingUtilities.invokeLater(() -> {
            // Aquí puedes decidir qué vista será la principal
            vistalogin vistaPrincipal = new vistalogin(); // La vista que quieres que sea la principal
            vistaPrincipal.setVisible(true); // Hacer visible la ventana principal
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private botones.boton boton1;
    private javax.swing.JPasswordField inputpassword;
    private javax.swing.JTextField inputusers;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage11;
    private rojerusan.RSLabelImage rSLabelImage12;
    // End of variables declaration//GEN-END:variables
}
